language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.m2
sudo: false
install: true
script: mvn package
env:
  global:
  - secure: "sLbmPD7lNoJUpC/D6hbQQIN+Ep/Fjc3qtpx320ll4Gh0lg7BFA5m78KFynhtlqQ+tj1MRHpqCBlrk9u7dWh2Z0cehjyG5wqjFr3or4a5avBHR/DkReVW5S5TQvHCwcgnKIzxF3eYwynxSNKuQ0/syz8//yAeodoSfMaOICTXESV/NdUdNUtQrZcJ0/kLwy9YUlfo0BS9iFA0fUbqBdxNLHIj0HO/mG7Gu2ytE3NCEMjbz5ht4d9Nn2bjFivVAkn+58af92NWv/ID4UcT5mPk/fWJb8qCsvTKMRV8fW3mdYbUjUmmhr6ilkiPZakQQqKb18MINFnIwVUC2i8rJgeXfQFy9KRJ9L2EfbhAI8o/uZ6LpHRR/D16KKokIW8IqSD7cCWu0gNxNTJvOLcvkcIhxSeUn9I9F+g03zQVQ1WO0cuuIXOK8aIkyBEuOSLS9/AQOSXQdPOdGTbj2cVox6PqGxuudFcvqsFguIfi19+599yXE/oOwf+vwNlag8Y0MAnxsOpXElavE39KOhO8JuduukE3wPu571pAFz31uxZMq1pDgk2y8AGhOV29P2KiwFeOU+kGl2jT15F/+71Py6c2KD2QF4G2IxhHd25FNOwH4cxn+yBqw6wbyDdsbed3WOjswMg1caq3nx8ehf51lIRH/w5A3ZDGN625nPFdh2KS0ew=" # DOCKER_EMAIL
  - secure: Cy8OUYjythkvNZJjbuvaYaIdNQFI7AdoA37xNyIJlq5YKU3gs+RYnAyVOBVaBunenBu0FtnuBXvkmkptrqB/uc758cQ8PGfkCz8XuTQvN/g34vpu7IXX4uTNiOpGQeh5VTWmwvycq4FW4jJlwXnHEyB3Bu31N5SCiT1LeKiEE7nZ67ag7tF5mwzZ5KZS/maQS+j/HlJhdVFc2I7U/BlHr0ysuFHztJELvkke63FvEmvPO4cUlQqR/+0oxXaVTXq1M4clGEAznkqi4gR3CWBY6o7uAGXjaP2IKfjhutcuutpsmUMA2gbxiEQIB0t0weRYLkcPIGaPP2KwS9QoiD9mp0M3p4R7W0zJJ7G0IcGlcHEZATtmxP6rmeOyzJZpgWz+CkDZ7YibxLoUPh3vUg+Mk2BwNhLXPtRKlUroNOmssib5TmqgsAThiHlZyakzvGD9pxikr6oQBYIQMU0X4QjwgRUDpL/csEQjvHcn/ASTcRF/pxmpObOZJqm1AxwhQL3juAo/WaB9VX4G8E6GxdJxnaI2Oa5cZdLS7PKOd05i9Kd5NDr6Cax1HVryeqON+t01Y2X2bxT0F76v8m+ObpUB6vLuBp1ijOjsS2TQXhVHKthYVmOC3ESFRWWN223T6yNbnJf6x9A79TWM3HueWmn7oEUeSKk11xZM224aQSuML8s= # DOCKER_USER
  - secure: rV5ximWjFd/Nny3X4e95ORl4rRSzFr78FB5xtwqpgeKg/ypYqla2NMdYfqOqFRDSYr34vj0d0njvsix65C7FZYrkdaR9uy2CEt6ROcbU+H4vcp3b4IdUwei6EnFQxMRL3NWoLDN+AvbvR5VYNY/5rLCbWOzGoBbIRGKnEeZOsEwj1zXkR8ANkBmZJ1NDn3tO7Wd7AcFPwlQnkkXxcSQPXD45ErhYb9YidbuQPWMJpCl1gtxT26pdVq5LXtJHu47ddUx6auMByJFRNP8Incp3kPbbU9OXG1Noi0GZ4c8rIU3Wca8e2UB1oLvPuPVfRsamHuxX3M3JQUaJhCZvvnvvYPm4rs+NCmezH4podM0e+ryA4osb9OxIdk2GJCCITWEd5Na/aapO3lIBnzpZVkxrsH8UQODdD4a22uPpqrIycu3q/8M0LkZT06epzvSn2JhVW3e34UlNKsczpb/9JZRseb+p1rlwS/ytSNpod0ESGw3ISGLRNIUtrxaKHj79vSA3CuAyXsZN+tJvqxsJ9Kw+6mDjtoO6c/OXY8tdcytRITIInyHc++Tqp9huYLiY+Ei5LHr+iNL7cCCDw6EptZgM+wNDqDD3bsETHC9CKdVZvGLt4MaVbe4sPAcr5k8M46EfWhigD5CRBwiPQTIoINixnq/8dWUIfaQiFC2RbBHngiQ= # DOCKER_PASS
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=portlandwebworks/chhs-backend
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - mvn docker:build
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
